"use client"
import Navbar from '@/Components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/Components/Footer'
import { usePathname } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  let pathname = usePathname()

  return (
    <html lang="en">
      <body className={inter.className}>
      { !pathname.includes("authentication") && !pathname.includes("administrator")  && <Navbar />}
      <div style={{flexGrow : 1}} >
      {children}
      </div>  
      { !pathname.includes("authentication") && !pathname.includes("administrator")  && <Footer />}
      </body>
    </html>
  )
}
